import { useMemo, useState } from 'react';
import StockBadge from '../components/StockBadge.jsx';
import EmptyState from '../components/EmptyState.jsx';
import ProductForm from './ProductForm.jsx';

export default function Products({ products, onAdd, onCreate, onUpdate, onDelete }) {
	const [query, setQuery] = useState('');
	const [stockFilter, setStockFilter] = useState('all');
	const [sort, setSort] = useState('name');
	const [showForm, setShowForm] = useState(false);
	const [editing, setEditing] = useState(null);
	const filtered = useMemo(() => products.filter(product => product.name.toLowerCase().includes(query.toLowerCase())).filter(product => stockFilter === 'all' || stockFilter === 'out' && product.stock === 0 || stockFilter === 'low' && product.stock > 0 && product.stock <= 5 || stockFilter === 'in' && product.stock > 5).sort((a, b) => sort === 'price' ? a.price - b.price : sort === 'stock' ? a.stock - b.stock : a.name.localeCompare(b.name)), [products, query, stockFilter, sort]);
	return <section><div className="page-heading"><div><p className="eyebrow">Live catalog</p><h1>Products</h1><p className="page-subtitle">Accurate availability from your inventory ledger.</p></div><div className="heading-actions"><span className="record-count">{filtered.length} products</span><button className="primary-button" onClick={() => { setEditing(null); setShowForm(value => !value); }}>+ Add product</button></div></div>{(showForm || editing) && <ProductForm product={editing} onSubmit={async product => { if (editing) await onUpdate(editing._id, product); else await onCreate(product); setShowForm(false); setEditing(null); }} onCancel={() => { setShowForm(false); setEditing(null); }} />}<div className="toolbar"><label className="search-field"><span>⌕</span><input value={query} onChange={event => setQuery(event.target.value)} placeholder="Search products" /></label><select value={stockFilter} onChange={event => setStockFilter(event.target.value)}><option value="all">All stock statuses</option><option value="in">In stock</option><option value="low">Low stock</option><option value="out">Out of stock</option></select><select value={sort} onChange={event => setSort(event.target.value)}><option value="name">Sort by name</option><option value="price">Sort by price</option><option value="stock">Sort by stock</option></select></div>{filtered.length ? <div className="product-grid">{filtered.map(product => <article className="product-card" key={product._id}><div className="product-art">{product.name.slice(0, 1).toUpperCase()}</div><div className="product-card-body"><span className="product-code">SKU {product._id.slice(-6).toUpperCase()}</span><h2>{product.name}</h2><p className="price">${Number(product.price).toFixed(2)}</p><div className="product-footer"><StockBadge stock={product.stock} /><button className="icon-button" disabled={!product.stock} onClick={() => onAdd(product)}>Add <span>+</span></button></div><div className="product-actions"><button className="edit-link" onClick={() => { setEditing(product); setShowForm(false); }}>Edit</button><button className="delete-link" onClick={() => onDelete(product)}>Delete</button></div></div></article>)}</div> : <EmptyState>No products match your filters.</EmptyState>}</section>;
}